### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by missinglink** [pelias/fuzzy-tester#38]
```
/var/www/pelias/fuzzy-tester/lib/request_urls.js:22
             res.body.geocoding.errors[0].message.indexOf('Request Timeout') !
                                                 ^
TypeError: Cannot read property 'indexOf' of undefined
    at shouldRetryRequest (/var/www/pelias/fuzzy-tester/lib/request_urls.js:22:50)
    at Request._callback (/var/www/pelias/fuzzy-tester/lib/request_urls.js:55:16)
    at Request.self.callback (/var/www/pelias/fuzzy-tester/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/var/www/pelias/fuzzy-tester/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/var/www/pelias/fuzzy-tester/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by missinglink** [comment]
the `errors` array only contains strings (same on prod and dev):

``` javascript
{
  "geocoding": {
    "version": "0.1",
    "attribution": "http:\/\/pelias.dev.mapzen.com\/v1\/attribution",
    "query": {
      "private": false
    },
    "errors": [
      "osm is invalid. It must be one of these values - [openstreetmap, openaddresses, geonames, quattroshapes, whosonfirst]"
    ],
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1456754656958
  },
  "type": "FeatureCollection",
  "features": [

  ]
}
```
