### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by missinglink** [pelias/fuzzy-tester#63]
```
npm test -o json
```

``` bash
/acceptance-tests/node_modules/pelias-fuzzy-tester/output_generators/json.js:33
  suiteResults.results.forEach( function ( suiteResult ) {
                      ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.prettyPrintSuiteResults [as outputGenerator] (/acceptance-tests/node_modules/pelias-fuzzy-tester/output_generators/json.js:33:23)
    at processResponses (/acceptance-tests/node_modules/pelias-fuzzy-tester/bin/fuzzy-tester:44:30)
    at Request._callback (/acceptance-tests/node_modules/pelias-fuzzy-tester/lib/request_urls.js:70:9)
    at Request.self.callback (/acceptance-tests/node_modules/pelias-fuzzy-tester/node_modules/request/request.js:200:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/acceptance-tests/node_modules/pelias-fuzzy-tester/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/acceptance-tests/node_modules/pelias-fuzzy-tester/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

```
$ grep version node_modules/pelias-fuzzy-tester/package.json 
  "version": "0.6.3",
```

```
$ node --version
v0.12.15
```

**Comment by orangejulius** [comment]
Oh...people use the json output? :open_mouth:

**Comment by dianashk** [comment]
Recent updates to the email output were made and should be replicated for json. see pelias/fuzzy-tester#57
